name: CI/CD Pipeline

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  linting-formatting:
    name: Linting and Formatting
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black flake8 isort mypy
    
    - name: Check code formatting with Black
      run: |
        black --check app/ tests/
    
    - name: Check import sorting with isort
      run: |
        isort --check-only app/ tests/
    
    - name: Lint with flake8
      run: |
        flake8 app/ tests/ --max-line-length=88 --extend-ignore=E203,W503
    
    - name: Type checking with mypy
      run: |
        mypy app/

  testing:
    name: Testing
    runs-on: ubuntu-latest
    needs: linting-formatting
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
    
    - name: Run tests with pytest
      run: |
        pytest --cov=app --cov-report=xml --cov-report=html
    
    - name: Upload coverage reports
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: htmlcov/
        retention-days: 30

  docker-build:
    name: Docker Build
    runs-on: ubuntu-latest
    needs: testing
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build Docker image
      run: |
        docker build -t my-python-app:latest .
    
    - name: Test Docker image
      run: |
        docker run --rm my-python-app:latest python -c "import sys; print('Python OK')"