name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  basic-test:
    name: Basic Python Test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Test Python environment
      run: |
        echo "🎉 GitHub Actions 工作正常!"
        python --version